---


# Required variables, break role if not provided
keepalived_instance: "VI_1"
keepalived_sync_groups: {VG1}
keepalived_global_router_id: "node"
keepalived_binding_interface: "enp0s3"
keepalived_virtual_ip: "192.168.1.1"

keepalived_auth_pass: "sys-ops"
keepalived_node_role: "BACKUP"
keepalived_virtual_router_id: "60"

keepalived_iptables_network: "192.168.0.0/24"
keepalived_global_smtp_server: "localhost"
# Set them only if specified by user
keepalived_node_priority: "100"
# keepalived_nopreempt: false
# keepalived_script_weight: 2
#
# Optional, monitor this interfaces as well.
# Keepalived will enter FAILED state if any of this go down.
# keepalived_tracked_interfaces:
#   - "eth0"
#   - "eth1"

sync_group.notify_master: "/usr/local/bin/Change_VRRP_Status.sh master"
sync_group.notify_backup: "/usr/local/bin/Change_VRRP_Status.sh backup"
sync_group.notify_fault: "/usr/local/bin/Change_VRRP_Status.sh fault"

keepalived_script_check_process: "teleport"
keepalived_script_interval: 2
keepalived_script_rise: 5

net_ipv4_conf_all_arp_ignore: 1
net_ipv4_conf_all_arp_announce: 2

log_dir: "/var/log"
keepalived_log_file: "{{ log_dir }}/keepalived.log"

# runtime settings
run_mode: Deploy
