---
# roles/keepalived/vars/RedHat.yml

iptables_save_bin: /sbin/iptables-save
dependencies:
  - "keepalived-{{ keepalived_version }}"
  # Fox killall tool
  - psmisc
  # For debugging
  - tcpdump
  - telnet
