---
# This role installs and sets up keepalived
# Copyright 2016-2017 FUJITSU LIMITED

- debug: msg="Running in >> {{ run_mode }} <<"

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Stop Keepalived process
  include: stop.yml
  when: run_mode == 'Stop'

- name: Install Keepalived
  include: install.yml
  when: run_mode == 'Install' or run_mode == 'Deploy'

- name: Configure Keepalived
  include: configure.yml
  when: run_mode == 'Configure' or run_mode == 'Deploy'

- name: Start Keepalived process
  include: start.yml
  when: run_mode == 'Start' or run_mode == 'Deploy'
